### PR TITLE
fix: Unable to upload more than 100MB of file

### LINKED ISSUE #9: Unable to upload more than 100MB of file
Hi Team.

I'm unable to upload the files which is having more than 100 MB but I'm able to upload the files from SAS Studiov successfully. 

And in EVM we have a limit of 2.5 GB which we can send.

Please assist where is the bug.

Thanks,
Shiva

### PR DESCRIPTION
**Pull request by sabhas**
closes #9

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -110,3 +167,19 @@ function populateTable(list) {
   })
   table.style.display = 'block'
 }
+
+function fileSize(bytes) {
```
Comment (YuryShkoda) [inline src/scripts.js]: would be nice to have such utility in `@sasjs/utils`

**Review by allanbowe — APPROVED** [review]
